# Generated by Django 6.0.3 on 2026-03-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_phone_verified',
            new_name='is_onboarding_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='onboarding_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
