# Generated by Django 6.0.3 on 2026-03-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='therapists/'),
        ),
    ]
