# Generated by Django 6.0.3 on 2026-03-19 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0002_therapist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='image',
            field=models.ImageField(upload_to='therapists/'),
        ),
    ]
